export const RouteEnum = {
  HOME: "/",
  // DASHBOARD: "/",
  LOGIN: "/login",
  SIGNUP: "/complete-signUp",
  DASHBOARD: "/dashboard",
  SIGNUPCLIENT: "/signup-client",
  MANAGE_COMPANIES: "/manage-companies",
  MANAGE_RIDERS: "/manage-riders",
  MANAGE_CUSTOMERS: "/manage-customers",
  TRIPS: "/trips",
  MAPS: "/maps",
  SUPPORT: "/support",
  SETTINGS: "/settings",
};
